models:
  RandomForest:
    n_estimators: [50, 100]
    max_depth: [10, 20]
    min_samples_split: [5]

  CatBoost:
    iterations: [100]
    depth: [6]
    learning_rate: [0.1]

  XGBoost:
    n_estimators: [100]
    max_depth: [6]
    learning_rate: [0.1]

  LinearRegression:
    fit_intercept: [true]

  GradientBoosting:
    n_estimators: [100]
    learning_rate: [0.1]
    max_depth: [5]

  AdaBoost:
    n_estimators: [50]
    learning_rate: [0.1]

  KNN:
    n_neighbors: [5]
    weights: ["uniform"]

  DecisionTree:
    max_depth: [10]
    min_samples_split: [5]
